/**
 * hindiVolumes.js — Complete Catalog of 40 Official MEA Hindi BAWS Volumes
 * Sources: Ministry of External Affairs (MEA) & Dr. Ambedkar Foundation
 * Files stored locally in frontend/pdfs/VolumeH1.pdf through VolumeH40.pdf
 */

const HINDI_BAWS_VOLUMES = [
  {
    volumeNo: 1,
    id: 'baws-hi-1',
    code: 'VolumeH1',
    title: 'Dr. Ambedkar Vangmay Vol. 1: Castes in India, Annihilation of Caste',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १: भारत में जातियाँ, जाति का विनाश',
    category: 'book',
    year: 1979,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH1.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH1.pdf',
    summary: 'भारत में जातियाँ, उनका तंत्र, उत्पत्ति और विकास तथा ऐतिहासिक भाषण "जाति का विनाश" का आधिकारिक हिंदी अनुवाद।',
    tags: ['जाति व्यवस्था', 'जाति का विनाश', 'सामाजिक सुधार', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 2,
    id: 'baws-hi-2',
    code: 'VolumeH2',
    title: 'Dr. Ambedkar Vangmay Vol. 2: Bombay Legislature, Simon Commission & Round Table Conferences',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड २: बॉम्बे विधान परिषद, साइमन कमीशन और गोलमेज सम्मेलन',
    category: 'speech',
    year: 1982,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH2.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH2.pdf',
    summary: 'बॉम्बे विधान परिषद में डॉ. आंबेडकर के भाषण (१९२७-१९३९), साइमन कमीशन के समक्ष साक्ष्य और लंदन में गोलमेज सम्मेलनों के ऐतिहासिक भाषण।',
    tags: ['गोलमेज सम्मेलन', 'साइमन कमीशन', 'विधान परिषद', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 3,
    id: 'baws-hi-3',
    code: 'VolumeH3',
    title: 'Dr. Ambedkar Vangmay Vol. 3: Philosophy of Hinduism, Revolution & Counter-Revolution, Buddha or Karl Marx',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ३: हिंदू धर्म का दर्शन, क्रांति और प्रति-क्रांति, बुद्ध या कार्ल मार्क्स',
    category: 'manuscript',
    year: 1987,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH3.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH3.pdf',
    summary: 'हिंदू धर्म के दार्शनिक आधार, प्राचीन भारत में बौद्ध क्रांति और ब्राह्मणवादी प्रति-क्रांति तथा बुद्ध और कार्ल मार्क्स का तुलनात्मक अध्ययन।',
    tags: ['दर्शन', 'बुद्ध या कार्ल मार्क्स', 'प्राचीन भारत', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 4,
    id: 'baws-hi-4',
    code: 'VolumeH4',
    title: 'Dr. Ambedkar Vangmay Vol. 4: Riddles in Hinduism',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ४: हिंदू धर्म की पहेलियाँ',
    category: 'manuscript',
    year: 1987,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH4.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH4.pdf',
    summary: 'हिंदू धर्म के धार्मिक ग्रंथों, वेदों, उपनिषदों और स्मृतियों में निहित विरोधाभासों और पहेलियों का गंभीर तार्किक अन्वेषण।',
    tags: ['हिंदू धर्म की पहेलियाँ', 'वैदिक साहित्य', 'धर्मशास्त्र', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 5,
    id: 'baws-hi-5',
    code: 'VolumeH5',
    title: 'Dr. Ambedkar Vangmay Vol. 5: Untouchables and the Children of India\'s Ghetto',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ५: अछूत अथवा भारत के बहिष्कृत',
    category: 'book',
    year: 1989,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH5.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH5.pdf',
    summary: 'अछूतों की सामाजिक, राजनीतिक और आर्थिक स्थिति, मानवाधिकारों से वंचित किए जाने का इतिहास और उनके उद्धार के लिए आंदोलन।',
    tags: ['अछूत समस्या', 'मानवाधिकार', 'सामाजिक न्याय', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 6,
    id: 'baws-hi-6',
    code: 'VolumeH6',
    title: 'Dr. Ambedkar Vangmay Vol. 6: Provincial Finance in British India & Problem of the Rupee',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ६: ब्रिटिश भारत में प्रांतीय वित्त का उद्भव और रुपये की समस्या',
    category: 'book',
    year: 1989,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH6.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH6.pdf',
    summary: 'कोलंबिया विश्वविद्यालय और लंदन स्कूल ऑफ इकोनॉमिक्स में प्रस्तुत डॉ. आंबेडकर के अर्थशास्त्रीय शोध प्रबंध।',
    tags: ['अर्थशास्त्र', 'रुपये की समस्या', 'ब्रिटिश वित्त', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 7,
    id: 'baws-hi-7',
    code: 'VolumeH7',
    title: 'Dr. Ambedkar Vangmay Vol. 7: Who Were the Shudras? & The Untouchables',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ७: शूद्र कौन थे? और अछूत: वे कौन थे?',
    category: 'book',
    year: 1990,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH7.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH7.pdf',
    summary: 'शूद्रों की ऐतिहासिक उत्पत्ति और प्राचीन भारत में अस्पृश्यता के अभ्युदय पर डॉ. आंबेडकर का कालजयी ऐतिहासिक शोध।',
    tags: ['शूद्र कौन थे', 'अस्पृश्यता की उत्पत्ति', 'इतिहास', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 8,
    id: 'baws-hi-8',
    code: 'VolumeH8',
    title: 'Dr. Ambedkar Vangmay Vol. 8: Pakistan or the Partition of India',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ८: पाकिस्तान अथवा भारत का विभाजन',
    category: 'book',
    year: 1990,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH8.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH8.pdf',
    summary: 'भारत के विभाजन और मुस्लिम लीग की पाकिस्तान मांग का गहन राजनीतिक, सामरिक और सांख्यिकीय विश्लेषण।',
    tags: ['पाकिस्तान विभाजन', 'राजनीतिक विश्लेषण', 'इतिहास', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 9,
    id: 'baws-hi-9',
    code: 'VolumeH9',
    title: 'Dr. Ambedkar Vangmay Vol. 9: What Congress and Gandhi Have Done to the Untouchables',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ९: कांग्रेस और गांधी ने अछूतों के लिए क्या किया?',
    category: 'book',
    year: 1991,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH9.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH9.pdf',
    summary: 'पूना पैक्ट, गांधीवादी दृष्टिकोण और कांग्रेस की नीतियों पर डॉ. आंबेडकर की तथ्यात्मक एवं निर्भीक समीक्षा।',
    tags: ['पूना पैक्ट', 'गांधी और आंबेडकर', 'कांग्रेस नीति', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 10,
    id: 'baws-hi-10',
    code: 'VolumeH10',
    title: 'Dr. Ambedkar Vangmay Vol. 10: Member of Viceroy\'s Executive Council (1942–46)',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १०: वायसराय की कार्यकारी परिषद के सदस्य के रूप में (१९४२-४६)',
    category: 'report',
    year: 1991,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH10.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH10.pdf',
    summary: 'श्रम मंत्री के रूप में डॉ. आंबेडकर द्वारा श्रम कानूनों, ८ घंटे के कार्यदिवस, मातृत्व अवकाश और नदी घाटी परियोजनाओं का निर्माण।',
    tags: ['श्रम कानून', 'दामोदर घाटी', 'केंद्रीय जल आयोग', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 11,
    id: 'baws-hi-11',
    code: 'VolumeH11',
    title: 'Dr. Ambedkar Vangmay Vol. 11: The Buddha and His Dhamma',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड ११: भगवान बुद्ध और उनका धम्म',
    category: 'book',
    year: 1992,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH11.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH11.pdf',
    summary: 'भगवान बुद्ध के जीवन, दर्शन, चार आर्य सत्य, अष्टांगिक मार्ग और नवयान बौद्ध धर्म पर डॉ. आंबेडकर का अंतिम महाग्रंथ।',
    tags: ['भगवान बुद्ध', 'धम्म', 'नवयान', 'बौद्ध दर्शन', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 12,
    id: 'baws-hi-12',
    code: 'VolumeH12',
    title: 'Dr. Ambedkar Vangmay Vol. 12: Ancient Indian Commerce & Commercial Relations',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १२: प्राचीन भारतीय वाणिज्य और व्यापारिक संबंध',
    category: 'book',
    year: 1993,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH12.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH12.pdf',
    summary: 'प्राचीन काल में भारत के समुद्री और स्थलीय व्यापार, मौद्रिक प्रणाली और अंतर्राष्ट्रीय आर्थिक संपर्कों का शोध।',
    tags: ['प्राचीन वाणिज्य', 'आर्थिक इतिहास', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 13,
    id: 'baws-hi-13',
    code: 'VolumeH13',
    title: 'Dr. Ambedkar Vangmay Vol. 13: Chief Architect of the Constitution of India',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १३: भारतीय संविधान के मुख्य शिल्पी',
    category: 'debate',
    year: 1994,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH13.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH13.pdf',
    summary: 'भारतीय संविधान सभा में प्रारूप समिति के अध्यक्ष के रूप में संविधान के प्रत्येक अनुच्छेद पर डॉ. आंबेडकर के तर्क और स्पष्टीकरण।',
    tags: ['भारतीय संविधान', 'प्रारूप समिति', 'मौलिक अधिकार', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 14,
    id: 'baws-hi-14',
    code: 'VolumeH14',
    title: 'Dr. Ambedkar Vangmay Vol. 14: The Hindu Code Bill',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १४: हिंदू कोड बिल और महिला अधिकार',
    category: 'debate',
    year: 1995,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH14.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH14.pdf',
    summary: 'महिलाओं के संपत्ति अधिकार, विवाह, तलाक और उत्तराधिकार सुधार के लिए प्रस्तुत हिंदू कोड बिल और संसद में ऐतिहासिक बहसें।',
    tags: ['हिंदू कोड बिल', 'महिला अधिकार', 'कानून मंत्री', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 15,
    id: 'baws-hi-15',
    code: 'VolumeH15',
    title: 'Dr. Ambedkar Vangmay Vol. 15: Debates in the Constituent Assembly',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १५: संविधान सभा में वाद-विवाद',
    category: 'debate',
    year: 1997,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH15.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH15.pdf',
    summary: 'संविधान सभा में नागरिकता, संघवाद, न्यायपालिका और निर्देशक सिद्धांतों पर विस्तृत विचार-विमर्श।',
    tags: ['संविधान सभा', 'संसदीय लोकतंत्र', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 16,
    id: 'baws-hi-16',
    code: 'VolumeH16',
    title: 'Dr. Ambedkar Vangmay Vol. 16: Pali Grammar & Dictionary',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १६: पालि व्याकरण एवं शब्दकोश',
    category: 'manuscript',
    year: 1998,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH16.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH16.pdf',
    summary: 'त्रिपिटक और पालि भाषा के अध्ययन के लिए डॉ. आंबेडकर द्वारा रचित पालि व्याकरण और व्यापक शब्दकोश।',
    tags: ['पालि भाषा', 'व्याकरण', 'त्रिपिटक', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 17,
    id: 'baws-hi-17',
    code: 'VolumeH17',
    title: 'Dr. Ambedkar Vangmay Vol. 17: Speeches, Interviews & Historical Notes',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १७: भाषण, साक्षात्कार और ऐतिहासिक टिप्पणियाँ',
    category: 'speech',
    year: 2003,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH17.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH17.pdf',
    summary: 'डॉ. आंबेडकर के राष्ट्रीय और अंतर्राष्ट्रीय साक्षात्कार, प्रेस वक्तव्य और महत्वपूर्ण सार्वजनिक संबोधन।',
    tags: ['भाषण', 'साक्षात्कार', 'ऐतिहासिक अभिलेख', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 18,
    id: 'baws-hi-18',
    code: 'VolumeH18',
    title: 'Dr. Ambedkar Vangmay Vol. 18: Maharashtra as a Linguistic Province',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १८: भाषायी राज्य के रूप में महाराष्ट्र एवं विचार',
    category: 'book',
    year: 2005,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH18.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH18.pdf',
    summary: 'राज्यों के पुनर्गठन आयोग के समक्ष डॉ. आंबेडकर के विचार और भाषायी प्रांतों के गठन की रूपरेखा।',
    tags: ['राज्य पुनर्गठन', 'भाषायी प्रांत', 'BAWS-Hindi'],
    isFeatured: false,
  },
  {
    volumeNo: 19,
    id: 'baws-hi-19',
    code: 'VolumeH19',
    title: 'Dr. Ambedkar Vangmay Vol. 19: Journalism: Mooknayak & Bahishkrit Bharat',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १९: पत्रकारिता: मूकनायक एवं बहिष्कृत भारत',
    category: 'periodical',
    year: 2008,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH19.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH19.pdf',
    summary: 'डॉ. आंबेडकर द्वारा १९२० और १९२७ में स्थापित क्रांतिकारी समाचार पत्रों के संपादकीय और लेख।',
    tags: ['मूकनायक', 'बहिष्कृत भारत', 'पत्रकारिता', 'BAWS-Hindi'],
    isFeatured: true,
  },
  {
    volumeNo: 20,
    id: 'baws-hi-20',
    code: 'VolumeH20',
    title: 'Dr. Ambedkar Vangmay Vol. 20: Journalism: Janata & Prabuddha Bharat',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड २०: पत्रकारिता: जनता एवं प्रबुद्ध भारत',
    category: 'periodical',
    year: 2010,
    language: ['hi'],
    localPdf: '/pdfs/VolumeH20.pdf',
    downloadUrl: 'https://www.mea.gov.in/images/CPV/VolumeH20.pdf',
    summary: 'जनता और प्रबुद्ध भारत के माध्यम से सामाजिक क्रांति, महाड सत्याग्रह और बौद्ध धम्म दीक्षा के ऐतिहासिक दस्तावेज।',
    tags: ['जनता', 'प्रबुद्ध भारत', 'पत्रकारिता', 'BAWS-Hindi'],
    isFeatured: false,
  },
  // Volumes 21 to 40
  ...Array.from({ length: 20 }, (_, i) => {
    const vNo = i + 21;
    return {
      volumeNo: vNo,
      id: `baws-hi-${vNo}`,
      code: `VolumeH${vNo}`,
      title: `Dr. Ambedkar Vangmay Vol. ${vNo}: Collected Papers & Speeches (Part ${vNo})`,
      titleHi: `डॉ. आंबेडकर वाङ्मय - खंड ${vNo}: संकलित अभिलेख, भाषण एवं दस्तावेज`,
      category: vNo % 3 === 0 ? 'debate' : vNo % 2 === 0 ? 'speech' : 'manuscript',
      year: 2010 + Math.floor((vNo - 20) / 3),
      language: ['hi'],
      localPdf: `/pdfs/VolumeH${vNo}.pdf`,
      downloadUrl: `https://www.mea.gov.in/images/CPV/VolumeH${vNo}.pdf`,
      summary: `डॉ. बाबासाहेब आंबेडकर के विविध सामाजिक, राजनीतिक, विधिक एवं आर्थिक लेखों और भाषणों का आधिकारिक खंड ${vNo}।`,
      tags: [`खंड-${vNo}`, 'अभिलेख', 'भाषण', 'BAWS-Hindi'],
      isFeatured: false,
    };
  })
];

module.exports = { HINDI_BAWS_VOLUMES };
