/**
 * meaVolumes.js — Official Catalog of Dr. Babasaheb Ambedkar Writings & Speeches (BAWS)
 * Source: Ministry of External Affairs (MEA) & Dr. Ambedkar Foundation (Ministry of Social Justice)
 * Contains Volumes 1 through 21 with full bilingual titles, chapter breakdowns, and metadata.
 */

const MEA_BAWS_VOLUMES = [
  {
    volumeNo: 1,
    title: 'Writings and Speeches: Castes in India, Annihilation of Caste, and Other Essays',
    titleHi: 'डॉ. आंबेडकर वाङ्मय - खंड १: भारत में जातियाँ, जाति का विनाश',
    titleMr: 'डॉ. आंबेडकर लेखन आणि भाषणे - खंड १: भारतातील जाती, जातीचे उच्चाटन',
    category: 'book',
    year: 1979,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India & Maharashtra State',
    pageCount: 512,
    summary: 'Contains Castes in India, Annihilation of Caste, Maharashtra as a Linguistic Province, States and Minorities, Ranade Gandhi and Jinnah, and Communal Deadlock.',
    tags: ['BAWS-Vol-1', 'Caste System', 'Constitutional Law', 'Social Reform'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_01.pdf'
  },
  {
    volumeNo: 2,
    title: 'Dr. Ambedkar in Bombay Legislature, Simon Commission & Round Table Conferences',
    titleHi: 'बॉम्बे विधान परिषद, साइमन कमीशन और गोलमेज सम्मेलन (१९२७-१९३९)',
    titleMr: 'मुंबई कायदेमंडळ, सायमन कमिशन आणि गोलमेज परिषद',
    category: 'speeches',
    year: 1982,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 780,
    summary: 'Proceedings of Dr. Ambedkar in the Bombay Legislative Council (1927-1939), evidence before the Simon Commission, and historic speeches at the 3 Round Table Conferences in London.',
    tags: ['BAWS-Vol-2', 'Round Table Conference', 'Bombay Legislature', 'Simon Commission'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_02.pdf'
  },
  {
    volumeNo: 3,
    title: 'Philosophy of Hinduism, Revolution and Counter-Revolution in Ancient India, Buddha or Karl Marx',
    titleHi: 'हिंदू धर्म का दर्शन, प्राचीन भारत में क्रांति और प्रति-क्रांति, बुद्ध या कार्ल मार्क्स',
    titleMr: 'हिंदू धर्माचे तत्त्वज्ञान, प्राचीन भारतातील क्रांती आणि प्रतिक्रांती',
    category: 'manuscript',
    year: 1987,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 498,
    summary: 'Profound philosophical essays dissecting the moral foundations of Hinduism, ancient Indian social upheavals, and a comparative study between Buddhist philosophy and Marxism.',
    tags: ['BAWS-Vol-3', 'Philosophy of Hinduism', 'Buddha or Karl Marx', 'Ancient History'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_03.pdf'
  },
  {
    volumeNo: 4,
    title: 'Riddles in Hinduism: An Exposition to Enlighten the Masses',
    titleHi: 'हिंदू धर्म की पहेलियाँ',
    titleMr: 'हिंदू धर्मातील कूटप्रश्न (रिडल्स इन हिंदुइझम)',
    category: 'manuscript',
    year: 1987,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 422,
    summary: 'A critical inquiry into religious scriptures, mythology, and ethical riddles embedded in orthodox texts.',
    tags: ['BAWS-Vol-4', 'Riddles in Hinduism', 'Scriptural Criticism'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_04.pdf'
  },
  {
    volumeNo: 5,
    title: 'Essays on Untouchables and Untouchability: Social, Political and Religious Aspect',
    titleHi: 'अछूत और अस्पृश्यता पर निबंध',
    titleMr: 'अस्पृश्य आणि अस्पृश्यतेवरील निबंध',
    category: 'manuscript',
    year: 1989,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 466,
    summary: 'Collection of unpublished essays documenting the social disabilities, economic boycotts, and religious sanctions imposed on untouchables.',
    tags: ['BAWS-Vol-5', 'Untouchability', 'Human Rights', 'Social Justice'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_05.pdf'
  },
  {
    volumeNo: 6,
    title: 'Economic Writings: Administration and Finance of East India Company, Evolution of Provincial Finance, Problem of the Rupee',
    titleHi: 'आर्थिक रचनाएँ: प्रांतीय वित्त का विकास एवं रुपये की समस्या',
    titleMr: 'आर्थिक लेखन: ईस्ट इंडिया कंपनीचे प्रशासन आणि प्रांतिक वित्तव्यवस्थेचा विकास',
    category: 'book',
    year: 1989,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 712,
    summary: 'Dr. Ambedkar\'s classic economic treatises for Columbia University and London School of Economics that inspired the founding principles of the Reserve Bank of India (RBI).',
    tags: ['BAWS-Vol-6', 'Economics', 'RBI', 'Problem of the Rupee', 'Finance'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_06.pdf'
  },
  {
    volumeNo: 7,
    title: 'Who Were the Shudras? & The Untouchables',
    titleHi: 'शूद्र कौन थे? और अछूत कौन थे?',
    titleMr: 'शूद्र पूर्वी कोण होते? व अस्पृश्य ते कोण होते?',
    category: 'book',
    year: 1990,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 404,
    summary: 'Historical and sociological research investigating how the Indo-Aryan society developed caste stratification and how broken men became untouchables.',
    tags: ['BAWS-Vol-7', 'Who Were Shudras', 'The Untouchables', 'Ancient India'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_07.pdf'
  },
  {
    volumeNo: 8,
    title: 'Pakistan or the Partition of India',
    titleHi: 'पाकिस्तान या भारत का विभाजन',
    titleMr: 'पाकिस्तान किंवा भारताची फाळणी',
    category: 'book',
    year: 1990,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 488,
    summary: 'Masterful geopolitical and constitutional analysis written in 1940 examining communal relations, defense, national security, and the demand for Pakistan.',
    tags: ['BAWS-Vol-8', 'Partition of India', 'Pakistan', 'Geopolitics'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_08.pdf'
  },
  {
    volumeNo: 9,
    title: 'What Congress and Gandhi Have Done to the Untouchables & Mr. Gandhi and Emancipation',
    titleHi: 'कांग्रेस और गांधी ने अछूतों के लिए क्या किया है',
    titleMr: 'काँग्रेस आणि गांधींनी अस्पृश्यांसाठी काय केले',
    category: 'book',
    year: 1991,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 440,
    summary: 'Detailed critique of political negotiations, Poona Pact implementation, and independent political representation for Depressed Classes.',
    tags: ['BAWS-Vol-9', 'Poona Pact', 'Gandhi', 'Political Representation'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_09.pdf'
  },
  {
    volumeNo: 10,
    title: 'Dr. Ambedkar as Member of the Governor-General’s Executive Council (1942–1946)',
    titleHi: 'गवर्नर जनरल की कार्यकारी परिषद के सदस्य के रूप में डॉ. आंबेडकर',
    titleMr: 'गव्हर्नर जनरलच्या कार्यकारी परिषदेचे सदस्य म्हणून डॉ. आंबेडकर',
    category: 'speeches',
    year: 1991,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1070,
    summary: 'Key policy speeches and legislative reforms introduced by Dr. Ambedkar as Labour Member, introducing 8-hour workday, maternity benefits, and Damodar Valley river projects.',
    tags: ['BAWS-Vol-10', 'Labour Laws', 'Executive Council', '8-Hour Workday', 'Water Resources'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_10.pdf'
  },
  {
    volumeNo: 11,
    title: 'The Buddha and His Dhamma',
    titleHi: 'भगवान बुद्ध और उनका धम्म',
    titleMr: 'भगवान बुद्ध आणि त्यांचा धम्म',
    category: 'book',
    year: 1992,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 620,
    summary: 'Dr. Ambedkar\'s magnum opus on Buddhist philosophy, presenting the life, teachings, rationalism, and moral code of Gautama Buddha.',
    tags: ['BAWS-Vol-11', 'Buddha and His Dhamma', 'Buddhism', 'Rationalism'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_11.pdf'
  },
  {
    volumeNo: 12,
    title: 'Unpublished Writings: Ancient Indian Commerce, Notes on Laws, Waiting for a Visa',
    titleHi: 'अप्रकाशित रचनाएँ: प्राचीन भारतीय व्यापार, वेटिंग फॉर ए वीजा',
    titleMr: 'अप्रकाशित लेख: प्राचीन भारतीय व्यापार आणि वेटिंग फॉर अ व्हिसा',
    category: 'manuscript',
    year: 1993,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 750,
    summary: 'Includes Dr. Ambedkar\'s famous autobiographical work "Waiting for a Visa", Columbia thesis on Ancient Indian Commerce, and legal drafts.',
    tags: ['BAWS-Vol-12', 'Waiting for a Visa', 'Autobiography', 'Commerce'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_12.pdf'
  },
  {
    volumeNo: 13,
    title: 'Dr. Ambedkar as the Principal Architect of the Constitution of India',
    titleHi: 'भारत के संविधान के मुख्य शिल्पकार के रूप में डॉ. आंबेडकर',
    titleMr: 'भारतीय संविधानाचे शिल्पकार म्हणून डॉ. आंबेडकर',
    category: 'constitution',
    year: 1994,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1210,
    summary: 'Comprehensive Constituent Assembly Debates, Drafting Committee proceedings, Article-by-Article commentary by Chairman Dr. B. R. Ambedkar.',
    tags: ['BAWS-Vol-13', 'Constituent Assembly', 'Constitution of India', 'Drafting Committee'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_13.pdf'
  },
  {
    volumeNo: 14,
    title: 'Dr. Ambedkar as Free India’s First Law Minister and Hindu Code Bill Debates (Parts 1 & 2)',
    titleHi: 'स्वतंत्र भारत के प्रथम कानून मंत्री एवं हिंदू कोड बिल बहस',
    titleMr: 'स्वतंत्र भारताचे पहिले कायदेमंत्री व हिंदु कोड बिल वादविवाद',
    category: 'speeches',
    year: 1995,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1380,
    summary: 'Parliamentary debates on the Hindu Code Bill for women\'s property rights, divorce rights, and legislative reforms, leading to his resignation as Law Minister.',
    tags: ['BAWS-Vol-14', 'Law Minister', 'Hindu Code Bill', 'Women Rights', 'Parliament'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_14.pdf'
  },
  {
    volumeNo: 15,
    title: 'Dr. Ambedkar in Parliament & Rajya Sabha Speeches (1952–1956)',
    titleHi: 'संसद एवं राज्यसभा में डॉ. आंबेडकर (१९५२-१९५६)',
    titleMr: 'संसद आणि राज्यसभेतील डॉ. आंबेडकरांची भाषणे',
    category: 'speeches',
    year: 1997,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1020,
    summary: 'Speeches delivered as Member of Opposition in Rajya Sabha on foreign policy, economic planning, states reorganization, and election laws.',
    tags: ['BAWS-Vol-15', 'Rajya Sabha', 'Parliament Speeches', 'Foreign Policy'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_15.pdf'
  },
  {
    volumeNo: 16,
    title: 'Dr. B. R. Ambedkar’s Pali Grammar & Pali Dictionary Notes',
    titleHi: 'डॉ. आंबेडकर कृत पालि व्याकरण और शब्दकोश',
    titleMr: 'डॉ. आंबेडकरांचे पालि व्याकरण',
    category: 'manuscript',
    year: 1998,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 540,
    summary: 'Linguistic study and instructional manual written by Dr. Ambedkar to revive the study of Pali language in India.',
    tags: ['BAWS-Vol-16', 'Pali Grammar', 'Linguistics', 'Pali Language'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_16.pdf'
  },
  {
    volumeNo: 17,
    title: 'Dr. B. R. Ambedkar and His Egalitarian Revolution (Parts 1, 2 & 3)',
    titleHi: 'डॉ. आंबेडकर और उनकी समतावादी क्रांति (भाग १, २, ३)',
    titleMr: 'डॉ. आंबेडकर आणि त्यांची समतावादी क्रांती',
    category: 'speeches',
    year: 2003,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1490,
    summary: 'Historical photo documentation, public addresses, speeches, and international greetings from 1920 to 1956.',
    tags: ['BAWS-Vol-17', 'Egalitarian Revolution', 'Speeches', 'Public Life'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_17.pdf'
  },
  {
    volumeNo: 18,
    title: 'Dr. Babasaheb Ambedkar Lekhan ani Bhashane (Marathi Compilation Parts 1–3)',
    titleHi: 'डॉ. बाबासाहेब आंबेडकर लेखन और भाषण (मराठी संकलन)',
    titleMr: 'डॉ. बाबासाहेब आंबेडकर लेखन आणि भाषणे (मराठी मूळ लेखन)',
    category: 'book',
    year: 2005,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1120,
    summary: 'Original Marathi speeches and writings delivered at conferences, Dalits movement rallies, and social gatherings across Maharashtra.',
    tags: ['BAWS-Vol-18', 'Marathi Speeches', 'Maharashtra Movement'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_18.pdf'
  },
  {
    volumeNo: 19,
    title: 'Dr. Babasaheb Ambedkar’s Journalism: Mooknayak (1920) & Bahishkrit Bharat (1927–1929)',
    titleHi: 'डॉ. आंबेडकर की पत्रकारिता: मूकनायक एवं बहिष्कृत भारत',
    titleMr: 'डॉ. बाबासाहेब आंबेडकरांची पत्रकारिता: मूकनायक आणि बहिष्कृत भारत',
    category: 'periodical',
    year: 2008,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 960,
    summary: 'Complete collection of editorials written by Dr. Ambedkar in Mooknayak (1920) and Bahishkrit Bharat (1927-1929).',
    tags: ['BAWS-Vol-19', 'Mooknayak', 'Bahishkrit Bharat', 'Journalism', 'Editorials'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_19.pdf'
  },
  {
    volumeNo: 20,
    title: 'Dr. Babasaheb Ambedkar’s Journalism: Janata (1930–1956) & Prabuddha Bharat (1956)',
    titleHi: 'डॉ. आंबेडकर की पत्रकारिता: जनता एवं प्रबुद्ध भारत',
    titleMr: 'डॉ. बाबासाहेब आंबेडकरांची पत्रकारिता: जनता आणि प्रबुद्ध भारत',
    category: 'periodical',
    year: 2010,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 1040,
    summary: 'Editorials and news commentaries published in Janata and Prabuddha Bharat covering freedom struggle, Mahad, and conversion to Buddhism.',
    tags: ['BAWS-Vol-20', 'Janata', 'Prabuddha Bharat', 'Journalism'],
    isFeatured: false,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_20.pdf'
  },
  {
    volumeNo: 21,
    title: 'Dr. B. R. Ambedkar’s Official Correspondence & Letters (1913–1956)',
    titleHi: 'डॉ. आंबेडकर का पत्राचार (१९१३-१९५६)',
    titleMr: 'डॉ. बाबासाहेब आंबेडकरांचा पत्रव्यवहार',
    category: 'manuscript',
    year: 2014,
    source: 'Ministry of External Affairs / Dr. Ambedkar Foundation',
    publisher: 'Government of India',
    pageCount: 880,
    summary: 'Personal and official correspondence of Dr. Ambedkar with Mahatma Gandhi, Jawaharlal Nehru, Lord Mountbatten, Columbia University professors, and international scholars.',
    tags: ['BAWS-Vol-21', 'Correspondence', 'Letters', 'History'],
    isFeatured: true,
    downloadUrl: 'https://www.mea.gov.in/Images/attach/amb/Volume_21.pdf'
  }
];

module.exports = { MEA_BAWS_VOLUMES };
